In [4]:
import pandas as pd
import numpy as np

In [ ]:
# Using Pandas we can create 2 kind of Objects
# 1. Series
# 2. DataFrame

In [3]:
# Series object using list
ser1 = pd.Series([21, 23, 24, 25, 30, 31])
print(ser1)

0    21
1    23
2    24
3    25
4    30
5    31
dtype: int64


In [4]:
print(type(ser1))

<class 'pandas.core.series.Series'>


In [5]:
ser2 = pd.Series({"roll_no":[101, 102, 103, 104, 105]})
ser2

roll_no    [101, 102, 103, 104, 105]
dtype: object

In [6]:
type(ser2)

pandas.core.series.Series

In [7]:
arr1 = np.arange(12,21)
arr1

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [9]:
ser3 = pd.Series(arr1)
ser3

0    12
1    13
2    14
3    15
4    16
5    17
6    18
7    19
8    20
dtype: int32

In [ ]:
# dtypes:It gives the data types 

In [15]:
ser3.dtypes

dtype('int32')

In [14]:
ser2.dtypes

dtype('O')

In [13]:
ser1.dtypes

dtype('int64')

In [ ]:
# continuous - numerical 
# categorical- object (O)

In [16]:
# index- It shows the index value 
ser1.index

RangeIndex(start=0, stop=6, step=1)

In [18]:
ser1.index=['a','b','c','d','e','f']
ser1

a    21
b    23
c    24
d    25
e    30
f    31
dtype: int64

In [19]:
ser4 = pd.Series([21,22,23,24],index=[101,102,103,104])
ser4

101    21
102    22
103    23
104    24
dtype: int64

In [20]:
# values- It converts Series object into array 
print(ser4.values)

[21 22 23 24]


In [22]:
newObj = ser4.values
newObj

array([21, 22, 23, 24], dtype=int64)

In [23]:
type(newObj)

numpy.ndarray

In [ ]:
# DataFrame- DataFrame has more than one columns.It is created using pd.DataFrame()

In [10]:
# From dict to DataFrame
df=pd.DataFrame({"Roll_No":[101,102,103,104], "Name":["Abc", "Def", "Ghi","Jkl"], "Gender":["M","F","F","F"]})
df

Roll_No Name Gender
0      101  Abc      M
1      102  Def      F
2      103  Ghi      F
3      104  Jkl      F

In [25]:
type(df)

pandas.core.frame.DataFrame

In [5]:
# From list to DataFrame
df1=pd.DataFrame([[101,"Mobile",25000], [102,"TV",34999],[103,"Tablet",18999]])
df1

0       1      2
0  101  Mobile  25000
1  102      TV  34999
2  103  Tablet  18999

In [27]:
# Using Array
arr1=np.array([101,102,103,104])
arr2=np.array(["M","M","F","F"])
df3=pd.DataFrame({"std_Id":arr1, "Gender":arr2})
df3

std_Id Gender
0     101      M
1     102      M
2     103      F
3     104      F

In [6]:
# slicing/subsetting
df1[0:3]

0       1      2
0  101  Mobile  25000
1  102      TV  34999
2  103  Tablet  18999

In [7]:
df1[0:3:2]

0       1      2
0  101  Mobile  25000
2  103  Tablet  18999

In [11]:
df

Roll_No Name Gender
0      101  Abc      M
1      102  Def      F
2      103  Ghi      F
3      104  Jkl      F

In [12]:
df["Roll_No"]

0    101
1    102
2    103
3    104
Name: Roll_No, dtype: int64

In [14]:
df[["Roll_No","Name"]]

Roll_No Name
0      101  Abc
1      102  Def
2      103  Ghi
3      104  Jkl

In [15]:
df["Roll_No"]>103

0    False
1    False
2    False
3     True
Name: Roll_No, dtype: bool

In [17]:
df[df["Roll_No"]>103]

Roll_No Name Gender
3      104  Jkl      F

In [19]:
# index based subsetting- iloc 
df.iloc[0:2, 0:2]

Roll_No Name
0      101  Abc
1      102  Def

In [20]:
df.loc[0:2,["Name","Gender"]]

Name Gender
0  Abc      M
1  Def      F
2  Ghi      F

In [22]:
data = pd.read_csv(r"D:\Data Science & AI\Pandas\assets\Data_File.csv")
data

Variable_A  Variable_B  Variable_C  Variable_D Variable_E
0          6.0         148          72          35          A
1          1.0          85          66          29          A
2          8.0         183          64           0          B
3          1.0          89          66          23          B
4          0.0         137          40          35          C
5          5.0         116          74           0          A
6          3.0          78          50          32          C
7         10.0         115           0           0        NaN
8          2.0         197          70          45          C
9          8.0         125          96           0          C
10         NaN         110          92           0          B
11        10.0         168          74           0          A
12        10.0         139          80           0          A
13         1.0         189          60          23          C

In [23]:
data[["Variable_A","Variable_E"]]

Variable_A Variable_E
0          6.0          A
1          1.0          A
2          8.0          B
3          1.0          B
4          0.0          C
5          5.0          A
6          3.0          C
7         10.0        NaN
8          2.0          C
9          8.0          C
10         NaN          B
11        10.0          A
12        10.0          A
13         1.0          C

In [24]:
data[0:8:2]

Variable_A  Variable_B  Variable_C  Variable_D Variable_E
0         6.0         148          72          35          A
2         8.0         183          64           0          B
4         0.0         137          40          35          C
6         3.0          78          50          32          C

In [26]:
data.loc[7:12,["Variable_C","Variable_E"]]

Variable_C Variable_E
7            0        NaN
8           70          C
9           96          C
10          92          B
11          74          A
12          80          A

In [27]:
data.iloc[[3,4,5,9], 0:3]

Variable_A  Variable_B  Variable_C
3         1.0          89          66
4         0.0         137          40
5         5.0         116          74
9         8.0         125          96

In [28]:
# Display only those values of Variable_B which are less then 150 
data["Variable_B"][data["Variable_B"]<150]

0     148
1      85
3      89
4     137
5     116
6      78
7     115
9     125
10    110
12    139
Name: Variable_B, dtype: int64